"""Starter TOML template for isentropic calculations."""

ISENTROPIC_SECTION = """\
[isentropic]
mach = 2.0
# pres_ratio = 0.1278
# temp_ratio = 0.5556
# dens_ratio = 0.2300
# area_ratio = 1.6875
branch = "supersonic"
gamma = 1.4
format = "json"
output = "isentropic.json"
"""

ISENTROPIC_TEMPLATE = """\
# Generated by: gasdyn isentropic init
# Edit the section below, then run: gasdyn isentropic run

""" + ISENTROPIC_SECTION
