"""Starter TOML template for normal-shock calculations."""

NORMAL_SHOCK_SECTION = """\
[normal_shock]
mach_1 = 2.0
# pres_ratio = 4.5
gamma = 1.4
format = "json"
output = "normal_shock.json"
"""

NORMAL_SHOCK_TEMPLATE = """\
# Generated by: gasdyn normal-shock init
# Edit the section below, then run: gasdyn normal-shock run

""" + NORMAL_SHOCK_SECTION
