"""Starter TOML template for Taylor-Maccoll calculations."""

TAYLOR_MACCOLL_SECTION = """\
[taylor_maccoll]
mach = 6.0
cone_angle = 7.0
# shock_angle = 12.0
gamma = 1.4
# beta_guess = 12.0
format = "json"
output = "taylor_maccoll.json"
# upstream_state = "flow_state.json"
# edge_state_output = "edge_state.json"
"""

TAYLOR_MACCOLL_TEMPLATE = (
    """\
# Generated by: gasdyn taylor-maccoll init
# Edit the section below, then run: gasdyn taylor-maccoll run

"""
    + TAYLOR_MACCOLL_SECTION
)
