"""Starter TOML template for isentropic calculations."""

ISENTROPIC_SECTION = """\
# --------------------------------------------------
# isentropic solver inputs
# --------------------------------------------------

[isentropic]
# provide exactly one of: mach, pres_ratio, temp_ratio, dens_ratio, area_ratio

# mach number
mach = 2.0

# static-to-stagnation pressure ratio (alternative input)
# pres_ratio = 0.1278

# static-to-stagnation temperature ratio (alternative input)
# temp_ratio = 0.5556

# static-to-stagnation density ratio (alternative input)
# dens_ratio = 0.2300

# area ratio A/A* (alternative input)
# area_ratio = 1.6875

# area-Mach solution branch: "subsonic" or "supersonic"
branch = "supersonic"

# ratio of specific heats
gamma = 1.4

# --------------------------------------------------
# output options
# --------------------------------------------------

# output format: "text" or "json"
format = "json"

# output file path
output = "isentropic.json"
"""

ISENTROPIC_TEMPLATE = (
    """\
# Generated by: gasdyn isentropic init
# Edit the section below, then run: gasdyn isentropic run

"""
    + ISENTROPIC_SECTION
)
