"""Starter TOML template for Prandtl-Meyer calculations."""

PRANDTL_MEYER_SECTION = """\
# --------------------------------------------------
# Prandtl-Meyer solver inputs
# --------------------------------------------------

[prandtl_meyer]
# provide exactly two of: mach_1, mach_2, deflection_angle

# upstream mach number
mach_1 = 2.0

# downstream mach number (alternative input)
# mach_2 = 3.0

# flow deflection angle [deg]
deflection_angle = 10.0

# ratio of specific heats
gamma = 1.4

# --------------------------------------------------
# output options
# --------------------------------------------------

# output format: "text" or "json"
format = "json"

# output file path
output = "prandtl_meyer.json"
"""

PRANDTL_MEYER_TEMPLATE = (
    """\
# Generated by: gasdyn prandtl-meyer init
# Edit the section below, then run: gasdyn prandtl-meyer run

"""
    + PRANDTL_MEYER_SECTION
)
