"""Starter TOML template for Prandtl-Meyer calculations."""

PRANDTL_MEYER_SECTION = """\
[prandtl_meyer]
mach_1 = 2.0
# mach_2 = 3.0
deflection_angle = 10.0
gamma = 1.4
format = "json"
output = "prandtl_meyer.json"
"""

PRANDTL_MEYER_TEMPLATE = """\
# Generated by: gasdyn prandtl-meyer init
# Edit the section below, then run: gasdyn prandtl-meyer run

""" + PRANDTL_MEYER_SECTION
