"""Starter TOML template for oblique-shock calculations."""

OBLIQUE_SECTION = """\
# --------------------------------------------------
# oblique-shock solver inputs
# --------------------------------------------------

[oblique]
# provide exactly two of: mach, deflection_angle, shock_angle

# upstream mach number
mach = 2.0

# flow deflection angle [deg]
deflection_angle = 10.0

# shock wave angle [deg] (alternative input)
# shock_angle = 39.3

# shock solution branch: "weak" or "strong"
branch = "weak"

# ratio of specific heats
gamma = 1.4

# --------------------------------------------------
# output options
# --------------------------------------------------

# output format: "text" or "json"
format = "json"

# output file path
output = "oblique.json"
"""

OBLIQUE_TEMPLATE = (
    """\
# Generated by: gasdyn oblique init
# Edit the section below, then run: gasdyn oblique run

"""
    + OBLIQUE_SECTION
)
