"""Starter TOML template for oblique-shock calculations."""

OBLIQUE_SECTION = """\
[oblique]
mach = 2.0
deflection_angle = 10.0
# shock_angle = 39.3
branch = "weak"
gamma = 1.4
format = "json"
output = "oblique.json"
"""

OBLIQUE_TEMPLATE = """\
# Generated by: gasdyn oblique init
# Edit the section below, then run: gasdyn oblique run

""" + OBLIQUE_SECTION
