"""Starter TOML template for normal-shock calculations."""

NORMAL_SHOCK_SECTION = """\
# --------------------------------------------------
# normal-shock solver inputs
# --------------------------------------------------

[normal_shock]
# provide exactly one of: mach_1, pres_ratio

# upstream mach number
mach_1 = 2.0

# downstream-to-upstream static pressure ratio (alternative input)
# pres_ratio = 4.5

# ratio of specific heats
gamma = 1.4

# --------------------------------------------------
# output options
# --------------------------------------------------

# output format: "text" or "json"
format = "json"

# output file path
output = "normal_shock.json"
"""

NORMAL_SHOCK_TEMPLATE = (
    """\
# Generated by: gasdyn normal-shock init
# Edit the section below, then run: gasdyn normal-shock run

"""
    + NORMAL_SHOCK_SECTION
)
