"""Starter TOML template for Taylor-Maccoll calculations."""

TAYLOR_MACCOLL_SECTION = """\
# --------------------------------------------------
# Taylor-Maccoll solver inputs
# --------------------------------------------------

[taylor_maccoll]
# without a pre-shock state, provide exactly two of: mach, cone_angle, shock_angle
# with a pre-shock state, provide exactly one of: cone_angle, shock_angle

# freestream mach number (optional consistency check with a pre-shock state)
mach = 6.0

# cone half-angle [deg]
cone_angle = 7.0

# shock wave angle [deg] (alternative input)
# shock_angle = 12.0

# ratio of specific heats (optional consistency check with a pre-shock state)
gamma = 1.4

# initial shock-angle guess [deg] (optional)
# beta_guess = 12.0

# dimensional pre-shock FlowState JSON input (requires a dimensional state output)
# pre_shock_state_input = "pre_shock_state.json"

# dimensionless Taylor-Maccoll solution JSON file
solution_output = "taylor_maccoll.json"

# dimensional state immediately behind the conical shock (optional)
# post_shock_state_output = "post_shock_state.json"

# dimensional cone-surface boundary-layer edge state (optional)
# edge_state_output = "edge_state.json"
"""

TAYLOR_MACCOLL_TEMPLATE = (
    """\
# Generated by: gasdyn taylor-maccoll init
# Edit the section below, then run: gasdyn taylor-maccoll run

"""
    + TAYLOR_MACCOLL_SECTION
)
